name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller pillow

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile resize.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: resized-app-exe
          path: dist/resize.exe
